# Generated by Django 5.0.2 on 2024-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='language',
            field=models.CharField(choices=[('Python', 'Python'), ('Cpp', 'Cpp'), ('Java', 'Java')], max_length=100),
        ),
    ]
