# Generated by Django 5.0.2 on 2024-05-25 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_code_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code',
            name='space_complexity',
        ),
    ]
